name: rinha-de-backend-2024
version: '3.5'

services:
  web:
    platform: linux/amd64
    # image: rinha-cledersonbd-app:latest
    build: ./
    ports:
      - "80:5000"
    volumes:
      - ./:/srv
    depends_on:
      db:
        condition: service_healthy

  db:
    platform: linux/amd64
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=rinha2024q1
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./app/db/script.sql:/docker-entrypoint-initdb.d/script.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d rinha "]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"
